### PR TITLE
updating repo for debian per http://www.go.cd/documentation/user/curr…

### PR DESCRIPTION
**Pull request by randomnumber9**
…ent/installation/install/server/linux.html

successfully ran on ubuntu 12.04 and 14.04

### CODE REVIEW

**Comment by jlyheden** [comment]
I will try to fix the broken rspec test setup first so we can test the pull

**Comment by jlyheden** [comment]
Could you pull in my rspec changes in your fork so it gets tested properly?

**Comment by randomnumber9** [comment]
Done.

**Comment by jlyheden** [comment]
Thx

**Pull request merged**
